### ISSUE TITLE
还原所有快捷方式选项时脚本报错

### ISSUE THREAD

**Issue by Vectorsmiracle** [Yuphiz/BaRestore_Startmenu#4]
当选择还原选项为还原所有用户快捷方式或者还原个人快捷方式是，脚本报错，默认选项无问题
![image](https://user-images.githubusercontent.com/22764532/165730120-39f0481d-ac6a-4de0-8778-d790ec39adf0.png)

**Comment by Yuphiz** [comment]
你的系统精简掉了资源管理器的zip解压缩功能，请自行手动用软件解压到目标文件夹
开始菜单user解压到%AppData%\Microsoft\Windows\Start Menu\Programs
开始菜单alluser解压到%ProgramData%\Microsoft\Windows\Start Menu\Programs

**Comment by Vectorsmiracle** [comment]
> 你的系统精简掉了资源管理器的zip解压缩功能，请自行手动用软件解压到目标文件夹 开始菜单user解压到%AppData%\Microsoft\Windows\Start Menu\Programs 开始菜单alluser解压到%ProgramData%\Microsoft\Windows\Start Menu\Programs

系统资源管理器有zip解压功能，之前使用的是很早的脚本，那个脚本还是可以正常使用
![image](https://user-images.githubusercontent.com/22764532/165877086-2ac8755d-475f-414e-94c3-bc25b0a02258.png)
然后用这个老版本还原新版本的备份是可以的

**Comment by Vectorsmiracle** [comment]
好像是备份的时候没有备份快捷方式
![image](https://user-images.githubusercontent.com/22764532/165877638-c3719b46-abcf-4d40-8ea8-9131224cd4b3.png)
对比用老脚本的备份，没有两个快捷方式的zip文件
![image](https://user-images.githubusercontent.com/22764532/165877992-d5a3403f-d906-4d81-a201-facb50ce0f48.png)
![image](https://user-images.githubusercontent.com/22764532/165878027-573dc820-fb3e-421d-8b12-b73f15f79f53.png)

**Comment by Yuphiz** [comment]
抱歉给你带来的麻烦。
你这个不只是少了zip文件，startmenulayout.xml也没有。猜测是你那边的powershell出了问题，请问你系统的powershell能用吗？
我这边也会用同样的系统测试一下

**Comment by Yuphiz** [comment]
你好，我这边复现问题了
当脚本所在路径或者备份路径存在空格时，有些备份就会失败。今天会修复这个bug
再次抱歉你遇到的问题。如果你不是迁移用户、重装系统，那么还原开始菜单备份.reg（不用还原快捷方式）已经足够了。如果你是新装系统、迁移用户等不存在快捷方式的情况，那么很抱歉，这些快捷方式不能找回来了。不过坏消息里还有好消息
1、如果不是自定义强制固定到开始菜单的快捷方式（比如.bat，.vbs，文件等强制固定到开始菜单），你装完那个软件，会自动出现在开始菜单
2、如果你是新装系统/新建用户，可能会因为快捷方式丢失而导致布局混乱，不过，当你手动还原/重装软件的快捷方式后，再使用还原（默认就好），布局也会回来的

**Comment by Yuphiz** [comment]
> 好像是备份的时候没有备份快捷方式 ![image](https://user-images.githubusercontent.com/22764532/165877638-c3719b46-abcf-4d40-8ea8-9131224cd4b3.png) 对比用老脚本的备份，没有两个快捷方式的zip文件 ![image](https://user-images.githubusercontent.com/22764532/165877992-d5a3403f-d906-4d81-a201-facb50ce0f48.png) ![image](https://user-images.githubusercontent.com/22764532/165878027-573dc820-fb3e-421d-8b12-b73f15f79f53.png)

你好，我这边复现问题了
当脚本所在路径或者备份路径存在空格时，有些备份就会失败。今天会修复这个bug
再次抱歉你遇到的问题。如果你不是迁移用户、重装系统，那么还原开始菜单备份.reg（不用还原快捷方式）已经足够了。如果你是新装系统、迁移用户等不存在快捷方式的情况，那么很抱歉，这些快捷方式不能找回来了。不过坏消息里还有好消息
1、如果不是自定义强制固定到开始菜单的快捷方式（比如.bat，.vbs，文件等强制固定到开始菜单），你装完那个软件，会自动出现在开始菜单
2、如果你是新装系统/新建用户，可能会因为快捷方式丢失而导致布局混乱，不过，当你手动还原/重装软件的快捷方式后，再使用还原（默认就好），布局也会回来的

**Comment by Yuphiz** [comment]
新版已修复此bug
下载：[releases](https://github.com/Yuphiz/BaRestore_Startmenu/releases/latest)

**Comment by Vectorsmiracle** [comment]
感谢修复，最新版没有问题了
