### ISSUE TITLE
打开新 GUI 时出现报错，无法打开注册键值

### ISSUE THREAD

**Issue by InoriILU** [Yuphiz/BaRestore_Startmenu#5]
如题，报错键值为
HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\\AppsUseLightTheme

环境为 win server 2019，内核为 1809 。
![image](https://user-images.githubusercontent.com/89334352/177250841-6f595fc5-9b82-426d-94c5-eb8c00670faa.png)

**Comment by Yuphiz** [comment]
你好，感谢提供bug。如错误提示， win server 2019可能没有那个控制主题颜色的注册表。读取这条注册表是为了切换主题。新版本增加了个判断，没有这条注册表就直接忽略，请试用0.6.2版本  
下载 [v0.6.2](https://github.com/Yuphiz/BaRestore_Startmenu/releases)

**Comment by Yuphiz** [comment]
> 如题，报错键值为 HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme
> 
> 环境为 win server 2019，内核为 1809 。 ![image](https://user-images.githubusercontent.com/89334352/177250841-6f595fc5-9b82-426d-94c5-eb8c00670faa.png)

你好，感谢提供bug。如错误提示， win server 2019可能没有那个控制主题颜色的注册表。读取这条注册表是为了切换主题。新版本增加了个判断，没有这条注册表就直接忽略，请试用0.6.2版本
下载 [v0.6.2](https://github.com/Yuphiz/BaRestore_Startmenu/releases)

**Comment by InoriILU** [comment]
蟹蟹老哥qwq

Your pulse, sigh, body temperature ―― your all, I am engraved in my heart.
________________________________
